In [1]:
import efficientnet.tfkeras as efn
from tensorflow import keras
import numpy as np
from skimage import io
from skimage.transform import rescale, resize, downscale_local_mean
import tensorflow as tf

In [2]:
def softmax(x):
    x -= np.max(x,axis=1, keepdims=True)
    a = np.exp(x)
    b = np.sum(np.exp(x), axis=1, keepdims=True)
    return a/b

In [4]:
model.load_weights('WHENet.h5')

In [16]:
model=tf.saved_model.load('1/model.savedmodel')

In [18]:
img=io.imread('face.png')
img=resize(img,(224,224))
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]
img = (img - mean) / std
img=img.astype('float32')

In [21]:
pred=model(np.array([img]))

In [24]:
pred

[<tf.Tensor: shape=(1, 120), dtype=float32, numpy=
 array([[ 1.3003943 , -0.6306996 ,  0.7934271 ,  0.6507559 ,  1.3842865 ,
          1.349395  ,  2.1160781 ,  1.4916598 ,  0.1692698 ,  1.7042153 ,
          1.3949298 ,  1.2580812 ,  0.5011635 ,  0.6220906 ,  2.082369  ,
          1.2927878 ,  1.6756572 ,  1.1855235 ,  1.9265068 ,  0.8719221 ,
          1.222812  ,  1.1345129 ,  1.2964942 ,  0.00628877,  1.1957009 ,
          1.144022  ,  1.5749238 ,  2.4951446 ,  1.9484104 ,  2.0993989 ,
          2.0163465 ,  1.536165  ,  1.3939227 ,  1.1995301 ,  1.3366029 ,
          0.8688964 ,  0.35959926,  3.106366  ,  1.2090111 ,  0.9097923 ,
          2.6122293 ,  1.7043307 ,  2.0087662 ,  0.8810147 ,  2.5941503 ,
          1.7795058 ,  1.8307683 ,  2.73325   ,  2.4304242 ,  1.4100857 ,
          1.1626943 ,  4.7776327 ,  0.9601601 ,  2.2209723 ,  1.8942499 ,
          4.4008946 ,  1.5104628 ,  1.1530901 ,  1.8874882 ,  1.174167  ,
          2.0467176 ,  3.658946  ,  2.904796  ,  2.9590347 , 

In [22]:
idx_tensor = [idx for idx in range(66)]
idx_tensor = np.array(idx_tensor, dtype=np.float32)
idx_tensor_yaw = [idx for idx in range(120)]
idx_tensor_yaw = np.array(idx_tensor_yaw, dtype=np.float32)
def get_angle(pred):
        yaw_predicted = softmax(pred[0])
        pitch_predicted = softmax(pred[1])
        roll_predicted = softmax(pred[2])
        yaw_predicted = np.sum(yaw_predicted*idx_tensor_yaw, axis=1)*3-180
        pitch_predicted = np.sum(pitch_predicted * idx_tensor, axis=1) * 3 - 99
        roll_predicted = np.sum(roll_predicted * idx_tensor, axis=1) * 3 - 99
        return yaw_predicted, pitch_predicted, roll_predicted

In [23]:
get_angle(pred)

(array([-20.462997], dtype=float32),
 array([7.847122], dtype=float32),
 array([-0.3040924], dtype=float32))